# Generated by Django 5.0.2 on 2025-07-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='nofollow_document',
            field=models.BooleanField(default=False, help_text='If True, all links to this page will have rel="nofollow".'),
        ),
    ]
