# Generated by Django 5.0.2 on 2025-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_page_nofollow_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='contact_box_color',
            field=models.CharField(default='#1e3a8a', help_text='Contact Box color (CSS hex)', max_length=32),
        ),
        migrations.AddField(
            model_name='website',
            name='header_box_color',
            field=models.CharField(default='rgba(20, 128, 138, 0.6)', help_text='Header Text Background Box color (CSS rgba or hex)', max_length=32),
        ),
        migrations.AddField(
            model_name='website',
            name='phone_banner_bg_color',
            field=models.CharField(default='#174d78', help_text='Phone banner background color (CSS hex)', max_length=32),
        ),
    ]
