# Generated by Django 5.0.2 on 2025-07-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_page_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='header_box_color',
            field=models.CharField(default='#14808a', help_text='Header Text Background Box color (CSS hex)', max_length=32),
        ),
    ]
