# Generated by Django 5.0.2 on 2025-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_alter_website_header_box_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='breadcrumb',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
