# Generated by Django 5.0.2 on 2025-07-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_author_website_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
